name: Linter and Jest
 
# Run this workflow every time a new commit pushed to your repository
on: 
  - push
 
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-lint-jest:
    # Name the Job
    name: Runs linter and Jest
    # Set the type of machine to run on
    runs-on: ubuntu-latest
 
    steps:
      # Check-out repository under GitHub workspace
      - uses: actions/checkout@v2
      # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
      # installing dependencies
      - name: install dependencies
        run: |
          make install
      # Add environment variables
        env:
          CI: true
      # Runs the Super-Linter action
      - name: Run Linter
        run: |
          make lint
      # Runs Jest tests
      - name: Run Jest
        run: |
          make test
      # Test Coverage
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.PANASI_SECRET }}
        with:
          coverageCommand: make test-coverage
          debug: true